2020-09-14 08:24:08,033 ERROR 11224 nodejs.ClusterClientNoResponseError: client no response in 19594475ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 11224
hostname: J9MO9BU01VTBF92

2020-09-14 08:38:54,692 ERROR 11224 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 11224
hostname: J9MO9BU01VTBF92

2020-09-14 11:14:11,042 ERROR 4768 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 4768
hostname: J9MO9BU01VTBF92

2020-09-14 12:43:03,108 ERROR 4768 nodejs.ClusterClientNoResponseError: client no response in 2667993ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 4768
hostname: J9MO9BU01VTBF92

2020-09-14 13:06:36,101 ERROR 4768 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 4768
hostname: J9MO9BU01VTBF92

2020-09-14 13:53:14,701 ERROR 2988 [-/127.0.0.1/-/39ms GET /verify] nodejs.Error: Cannot send secure cookie over unencrypted connection
    at Cookies.set (D:\energy-platform-project\energy-platform-server\node_modules\egg-cookies\lib\cookies.js:97:13)
    at ContextSession.save (D:\energy-platform-project\energy-platform-server\node_modules\koa-session\lib\context.js:338:22)
    at ContextSession.commit (D:\energy-platform-project\energy-platform-server\node_modules\koa-session\lib\context.js:239:16)
    at session (D:\energy-platform-project\energy-platform-server\node_modules\koa-session\index.js:46:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async bodyParser (D:\energy-platform-project\energy-platform-server\node_modules\koa-bodyparser\index.js:95:5)
    at async D:\energy-platform-project\energy-platform-server\node_modules\koa-static-cache\index.js:41:56
    at async notfound (D:\energy-platform-project\energy-platform-server\node_modules\egg\app\middleware\notfound.js:5:5)
    at async meta (D:\energy-platform-project\energy-platform-server\node_modules\egg\app\middleware\meta.js:12:5)
    at async cors (D:\energy-platform-project\energy-platform-server\node_modules\@koa\cors\index.js:56:32)

pid: 2988
hostname: J9MO9BU01VTBF92

2020-09-14 13:53:20,292 ERROR 2988 [-/127.0.0.1/-/7ms GET /verify] nodejs.Error: Cannot send secure cookie over unencrypted connection
    at Cookies.set (D:\energy-platform-project\energy-platform-server\node_modules\egg-cookies\lib\cookies.js:97:13)
    at ContextSession.save (D:\energy-platform-project\energy-platform-server\node_modules\koa-session\lib\context.js:338:22)
    at ContextSession.commit (D:\energy-platform-project\energy-platform-server\node_modules\koa-session\lib\context.js:239:16)
    at session (D:\energy-platform-project\energy-platform-server\node_modules\koa-session\index.js:46:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async bodyParser (D:\energy-platform-project\energy-platform-server\node_modules\koa-bodyparser\index.js:95:5)
    at async D:\energy-platform-project\energy-platform-server\node_modules\koa-static-cache\index.js:41:56
    at async notfound (D:\energy-platform-project\energy-platform-server\node_modules\egg\app\middleware\notfound.js:5:5)
    at async meta (D:\energy-platform-project\energy-platform-server\node_modules\egg\app\middleware\meta.js:12:5)
    at async cors (D:\energy-platform-project\energy-platform-server\node_modules\@koa\cors\index.js:56:32)

pid: 2988
hostname: J9MO9BU01VTBF92

2020-09-14 14:10:17,574 ERROR 4768 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 4768
hostname: J9MO9BU01VTBF92

2020-09-14 15:46:18,500 ERROR 4768 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 4768
hostname: J9MO9BU01VTBF92

2020-09-14 17:21:39,192 ERROR 1548 [-/192.168.0.246/-/22ms POST /devices/update] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'deviceID' in 'field list'
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: UPDATE `devices` SET `deviceID` = '', `deviceLevel` = '一般', `gatewayName` = '', `gatewayID` = '', `address` = '', `iceType` = '', `devicePlace` = 'K4-大厅', `id` = 1 WHERE `id` = 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'deviceID' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `devices` SET `deviceID` = '', `deviceLevel` = '一般', `gatewayName` = '', `gatewayID` = '', `address` = '', `iceType` = '', `devicePlace` = 'K4-大厅', `id` = 1 WHERE `id` = 1"
name: "ER_BAD_FIELD_ERRORError"
pid: 1548
hostname: J9MO9BU01VTBF92

2020-09-14 21:16:28,255 ERROR 10088 nodejs.ClusterClientNoResponseError: client no response in 10816046ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 10088
hostname: J9MO9BU01VTBF92

2020-09-15 00:16:30,984 ERROR 10088 nodejs.ClusterClientNoResponseError: client no response in 10802578ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 10088
hostname: J9MO9BU01VTBF92

