2020-11-22 00:29:29,873 INFO 13952 [egg-logrotator] agent logger reload: got log-reload message
2020-11-22 00:39:30,093 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 280197ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 00:44:29,582 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 159479ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 00:49:29,785 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 160191ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 00:54:30,487 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 160539ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 00:59:30,083 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 159352ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:04:30,691 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 100247ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:09:29,860 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 159160ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:14:29,565 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 159540ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:19:29,576 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 159869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:24:29,607 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 160024ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:29:30,518 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 160722ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:34:30,606 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 159870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:39:30,371 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 159559ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:44:29,984 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 159601ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:49:30,749 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 160430ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 01:54:30,546 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 159633ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 04:56:54,689 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 10803579ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 07:56:55,725 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 10801032ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 10:56:58,887 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 10803158ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 13:57:02,199 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 10803246ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 16:57:03,601 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 10801394ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 19:57:06,638 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 10803029ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-22 22:57:08,840 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 10802198ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

2020-11-23 00:20:30,190 ERROR 13952 nodejs.ClusterClientNoResponseError: client no response in 5001303ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\energy-platform-project\energy-platform-server\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 13952
hostname: J9MO9BU01VTBF92

