2020-09-21 09:17:37,942 WARN 14828 [-/192.168.0.174/-/12ms POST /user/delete] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (D:\energy-platform-project\energy-platform-server\node_modules\koa\lib\context.js:97:11)
    at Object.validate (D:\energy-platform-project\energy-platform-server\node_modules\egg-validate\app\extend\context.js:14:17)
    at UsreController.deleteuser (D:\energy-platform-project\energy-platform-server\app\controller\user.js:70:13)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:44:32)
    at next (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:45:18)
    at D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"required","field":"id","code":"missing_field"}]
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:18:20,752 ERROR 14828 [-/192.168.0.174/-/16ms POST /user/add] nodejs.ER_TRUNCATED_WRONG_VALUEError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2020-09-21T01:09:44.000Z' for column 'createTime' at row 1
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`id`, `username`, `password`, `email`, `createTime`, `company`, `loginTime`) VALUES(3, 'test22', '12345622', NULL, '2020-09-21T01:09:44.000Z', '鸿鹄信息科技1', '2020-09-21T01:09:44.000Z')
code: "ER_TRUNCATED_WRONG_VALUE"
errno: 1292
sqlMessage: "Incorrect datetime value: '2020-09-21T01:09:44.000Z' for column 'createTime' at row 1"
sqlState: "22007"
index: 0
sql: "INSERT INTO `user`(`id`, `username`, `password`, `email`, `createTime`, `company`, `loginTime`) VALUES(3, 'test22', '12345622', NULL, '2020-09-21T01:09:44.000Z', '鸿鹄信息科技1', '2020-09-21T01:09:44.000Z')"
name: "ER_TRUNCATED_WRONG_VALUEError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:18:28,187 ERROR 14828 [-/192.168.0.174/-/5ms POST /user/add] nodejs.ER_TRUNCATED_WRONG_VALUEError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2020-09-21T01:09:44.000Z' for column 'createTime' at row 1
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`id`, `username`, `password`, `email`, `createTime`, `company`, `loginTime`) VALUES(3, 'test22', '12345622', NULL, '2020-09-21T01:09:44.000Z', '鸿鹄信息科技1', '2020-09-21T01:09:44.000Z')
code: "ER_TRUNCATED_WRONG_VALUE"
errno: 1292
sqlMessage: "Incorrect datetime value: '2020-09-21T01:09:44.000Z' for column 'createTime' at row 1"
sqlState: "22007"
index: 0
sql: "INSERT INTO `user`(`id`, `username`, `password`, `email`, `createTime`, `company`, `loginTime`) VALUES(3, 'test22', '12345622', NULL, '2020-09-21T01:09:44.000Z', '鸿鹄信息科技1', '2020-09-21T01:09:44.000Z')"
name: "ER_TRUNCATED_WRONG_VALUEError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:18:59,690 WARN 14828 [-/192.168.0.174/-/5ms POST /user/update] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (D:\energy-platform-project\energy-platform-server\node_modules\koa\lib\context.js:97:11)
    at Object.validate (D:\energy-platform-project\energy-platform-server\node_modules\egg-validate\app\extend\context.js:14:17)
    at UsreController.updateuser (D:\energy-platform-project\energy-platform-server\app\controller\user.js:100:13)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:44:32)
    at next (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:45:18)
    at D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"required","field":"emailCode","code":"missing_field"}]
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:22:09,889 WARN 14828 [-/192.168.0.174/-/2ms POST /user/update] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (D:\energy-platform-project\energy-platform-server\node_modules\koa\lib\context.js:97:11)
    at Object.validate (D:\energy-platform-project\energy-platform-server\node_modules\egg-validate\app\extend\context.js:14:17)
    at UsreController.updateuser (D:\energy-platform-project\energy-platform-server\app\controller\user.js:100:13)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:44:32)
    at next (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:45:18)
    at D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"required","field":"emailCode","code":"missing_field"}]
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:23:53,431 ERROR 14828 [-/192.168.0.174/-/14ms POST /user/add] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '测试1' for key '_company'
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `password`, `company`) VALUES('test2', '1234562', '测试1')
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '测试1' for key '_company'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `user`(`username`, `password`, `company`) VALUES('test2', '1234562', '测试1')"
name: "ER_DUP_ENTRYError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:24:23,163 ERROR 14828 [-/192.168.0.174/-/6ms POST /user/add] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '测试1' for key '_company'
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `password`, `company`) VALUES('test2', '1234562', '测试1')
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '测试1' for key '_company'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `user`(`username`, `password`, `company`) VALUES('test2', '1234562', '测试1')"
name: "ER_DUP_ENTRYError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:24:28,656 WARN 14828 [-/192.168.0.174/-/1ms POST /user/delete] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (D:\energy-platform-project\energy-platform-server\node_modules\koa\lib\context.js:97:11)
    at Object.validate (D:\energy-platform-project\energy-platform-server\node_modules\egg-validate\app\extend\context.js:14:17)
    at UsreController.deleteuser (D:\energy-platform-project\energy-platform-server\app\controller\user.js:70:13)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:44:32)
    at next (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:45:18)
    at D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"required","field":"id","code":"missing_field"}]
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:25:18,645 WARN 14828 [-/192.168.0.174/-/1ms POST /user/update] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (D:\energy-platform-project\energy-platform-server\node_modules\koa\lib\context.js:97:11)
    at Object.validate (D:\energy-platform-project\energy-platform-server\node_modules\egg-validate\app\extend\context.js:14:17)
    at UsreController.updateuser (D:\energy-platform-project\energy-platform-server\app\controller\user.js:100:13)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:44:32)
    at next (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:45:18)
    at D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"required","field":"emailCode","code":"missing_field"}]
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:25:37,982 ERROR 14828 [-/192.168.0.174/-/19ms POST /user/add] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '测试1' for key '_company'
    at Query.Sequence._packetToError (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (D:\energy-platform-project\energy-platform-server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\energy-platform-project\energy-platform-server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:65:19)
    at D:\energy-platform-project\energy-platform-server\node_modules\co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `password`, `company`, `email`) VALUES('2222', '222', '测试1', '2222')
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '测试1' for key '_company'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `user`(`username`, `password`, `company`, `email`) VALUES('2222', '222', '测试1', '2222')"
name: "ER_DUP_ENTRYError"
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:28:15,335 WARN 14828 [-/192.168.0.174/-/2ms POST /user/update] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (D:\energy-platform-project\energy-platform-server\node_modules\koa\lib\context.js:97:11)
    at Object.validate (D:\energy-platform-project\energy-platform-server\node_modules\egg-validate\app\extend\context.js:14:17)
    at UsreController.updateuser (D:\energy-platform-project\energy-platform-server\app\controller\user.js:100:13)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:44:32)
    at next (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:45:18)
    at D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"required","field":"emailCode","code":"missing_field"}]
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 09:41:05,000 WARN 14828 [-/192.168.0.174/-/2ms POST /user/delete] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (D:\energy-platform-project\energy-platform-server\node_modules\koa\lib\context.js:97:11)
    at Object.validate (D:\energy-platform-project\energy-platform-server\node_modules\egg-validate\app\extend\context.js:14:17)
    at UsreController.deleteuser (D:\energy-platform-project\energy-platform-server\app\controller\user.js:70:13)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:44:32)
    at next (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:45:18)
    at D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"required","field":"id","code":"missing_field"}]
pid: 14828
hostname: J9MO9BU01VTBF92

2020-09-21 11:06:08,138 WARN 14828 [-/192.168.0.174/-/22ms POST /mail] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (D:\energy-platform-project\energy-platform-server\node_modules\koa\lib\context.js:97:11)
    at Object.validate (D:\energy-platform-project\energy-platform-server\node_modules\egg-validate\app\extend\context.js:14:17)
    at MailController.sendMail (D:\energy-platform-project\energy-platform-server\app\controller\mail.js:16:13)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (D:\energy-platform-project\energy-platform-server\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:44:32)
    at next (D:\energy-platform-project\energy-platform-server\node_modules\koa-compose\index.js:45:18)
    at D:\energy-platform-project\energy-platform-server\node_modules\@eggjs\router\lib\router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"should not be empty","code":"invalid","field":"email"}]
pid: 14828
hostname: J9MO9BU01VTBF92

